-- Update UAE Visa DSR Template to match 41-column CSV export structure
-- This migration updates the 'columns' JSONB to match the exact requirement

UPDATE public.dsr_templates
SET columns = '[
  {"key":"id","label":"ID","type":"text"},
  {"key":"record_time","label":"Record Time","type":"date"},
  {"key":"status","label":"Status","type":"text"},
  {"key":"type","label":"Type","type":"text"},
  {"key":"type_dr","label":"Type DR","type":"text"},
  {"key":"type_op","label":"Type OP","type":"text"},
  {"key":"nationality","label":"Nationality","type":"text"},
  {"key":"first_name","label":"First Name","type":"text"},
  {"key":"middle_name","label":"Middle Name","type":"text"},
  {"key":"last_name","label":"Last Name","type":"text"},
  {"key":"passport_no","label":"Passport No.","type":"text"},
  {"key":"expiry","label":"Expiry","type":"date"},
  {"key":"uid","label":"U.I.D.","type":"text"},
  {"key":"birth_date","label":"Birth Date","type":"date"},
  {"key":"arrival_date","label":"Arrival Date","type":"date"},
  {"key":"request_date","label":"Request Date","type":"date"},
  {"key":"debtor","label":"Debtor","type":"text"},
  {"key":"dr_title","label":"DR Title","type":"text"},
  {"key":"dr_reference","label":"DR Reference","type":"text"},
  {"key":"debt","label":"Debt","type":"number","financial":"sale"},
  {"key":"debt_vat","label":"Debt VAT","type":"number"},
  {"key":"debt_insurance","label":"Debt Insurance","type":"number"},
  {"key":"debt_guarantee","label":"Debt Guarantee","type":"number"},
  {"key":"creditor","label":"Creditor","type":"text"},
  {"key":"cr_title","label":"CR Title","type":"text"},
  {"key":"cr_reference","label":"CR Reference","type":"text"},
  {"key":"credit","label":"Credit","type":"number","financial":"cost"},
  {"key":"credit_vat","label":"Credit VAT","type":"number"},
  {"key":"credit_insurance","label":"Credit Insurance","type":"number"},
  {"key":"credit_guarantee","label":"Credit Guarantee","type":"number"},
  {"key":"fine","label":"Fine","type":"number"},
  {"key":"visa_validity","label":"Visa Validity","type":"text"},
  {"key":"last_date","label":"Last Date","type":"date"},
  {"key":"source","label":"Source","type":"text"},
  {"key":"group","label":"Group","type":"text"},
  {"key":"discounted_fm","label":"Discounted FM","type":"text"},
  {"key":"app_src","label":"App SRC","type":"text"},
  {"key":"app_id","label":"App ID","type":"text"},
  {"key":"visa_no","label":"Visa No.","type":"text"},
  {"key":"user","label":"User","type":"text"},
  {"key":"visa_comments","label":"Visa Comments","type":"textarea"},
  {"key":"profit","label":"Profit","type":"number","financial":"profit"}
]'::jsonb,
updated_at = now()
WHERE template_key = 'uae_visa';
